### ISSUE TITLE
License or Usage Rights Compontent

### ISSUE THREAD

**Issue by michael-collins** [LRNWebComponents/hax-body#101]
Purpose of component is to inform readers about desired usage of your copyrighted materials.

We should include license and usage information support for: 
   - [ ] http://rightsstatements.org/page/1.0/?language=en
   - [ ] Creative Commons
   - [ ] "Fair Use" with icon: https://commons.wikimedia.org/wiki/File:Fair_use_logo.svg (https://www.copyright.gov/fair-use/more-info.html)

**Fields:**

- Title
- Creator
- Source Link
- Selected Usage rights Type (CC, rightsusage.org, fairuse, etc.) (Autolinks to explanation)
- Scope
- Make license visible on page (default to on)

**Comment by btopro** [comment]
Is this just a wrapper on a citation element to make it set certain things automatically? Much like how wikipedia-query forces access date to the current date -- https://lrnwebcomponents.github.io/wikipedia-query/components/wikipedia-query/demo/

If this is a specific type of citation (self citation basically to inform others) then I can work off of that as a base element so that we can enhance citations to support stuff this would end up wanting

**Comment by btopro** [comment]
https://wiki.creativecommons.org/wiki/CCPlus example to componentize

**Comment by btopro** [comment]
```
<span xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/terms/">
 
<span rel="dc:type" href="http://purl.org/dc/dcmitype/Text" property="dc:title">My Book</span> by 
<a rel="cc:attributionURL" property="cc:attributionName" href="http://rejon.org/my_book">Jon Phillips</a> 
 
is licensed under a 
 
<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons 
Attribution Non-Commercial 3.0 License</a>. 
 
<span rel="dc:source" href="http://deerfang.org/her_book"/>
Permissions beyond the scope of this license may be available at 
<a rel="cc:morePermissions" 
href="http://somecompany.com/revenue_sharing_agreement">somecompany.com</a>.
 
</span>
```

**Comment by btopro** [comment]
CC+
```
<span xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/">
 
<span rel="dc:type" href="http://purl.org/dc/dcmitype/Text" property="dc:title">My Book</span> by 
<a rel="cc:attributionURL" property="cc:attributionName" href="http://rejon.org/my_book">Jon Phillips</a> 
 
is licensed under a 
 
<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons 
Attribution Non-Commercial 3.0 License</a>. 
 
<span rel="dc:source" href="http://deerfang.org/her_book"/>
Permissions beyond the scope of this license may be available at 
<a rel="cc:morePermissions" 
href="http://somecompany.com/revenue_sharing_agreement">somecompany.com</a>.
 
</span>
```

**Comment by btopro** [comment]
@michael-collins start at least. Let me know what to do from here -- https://github.com/LRNWebComponents/license-element

**Comment by michael-collins** [comment]
Is it possible to not print out text if a field/property is empty? "Permissions beyond the scope of this license may be available at " May not often be filled out, for instance.

**Comment by btopro** [comment]
ahh meant to do that but forgot, good suggestion. updated now.

**Comment by btopro** [comment]
![2018-05-14_08-38-33](https://user-images.githubusercontent.com/329735/39997888-647340a4-5752-11e8-91ef-4ba3f997bdee.png)

![2018-05-14_08-39-00](https://user-images.githubusercontent.com/329735/39997894-6636dd2e-5752-11e8-8f42-e023d779a927.png)
