### ISSUE TITLE
Can't figure out the delete paragraph in game

### ISSUE THREAD

**Issue by kreynen** [LRNWebComponents/hax-body#110]
I created text and then deleted it, but couldn't get that to check

**Comment by btopro** [comment]
huh?

**Comment by kreynen** [comment]
I created text and then deleted it assuming that was a paragraph.  Do I have to do these in a specific order?  Are you looking to see if I deleted a paragraph that existed on load?  Am I supposed to delete just a paragraph within text not the entire text asset/element?

![screen shot 2018-05-14 at 2 25 22 pm](https://user-images.githubusercontent.com/385234/40021738-f33d7a4a-5782-11e8-94de-45ed3bfe3a8c.png)

**Comment by btopro** [comment]
Oooooo the game. The game only seems to track paragraphs deleted in the middle of the page for some reason :p

**Comment by btopro** [comment]
just took it out of the game; the delete element observer is a little hard to effectively trap and report; especailly given that it's for playing a game :)
