### ISSUE TITLE
disable / grey out there upload feature in add if no backends present

### ISSUE THREAD

**Issue by btopro** [LRNWebComponents/hax-body#127]
as identified here -- https://github.com/elmsln/grav-plugin-hax/issues/6#issuecomment-394540420

it's a good idea to disable the upload field in the event that an implementation has no backend with which to upload to.

**Comment by mgifford** [comment]
Ideally a user would just see a link where they could attach an image, rather than somewhere that they might indicate that an upload is possible. When playing around with new technology, nobody wants to see an error.

**Comment by btopro** [comment]
![2018-06-05_11-57-20](https://user-images.githubusercontent.com/329735/40987831-8fdaf72a-68b7-11e8-9c58-ae0d2965ea7c.png)

so like this or are you referencing osmething else? URL field allows referencing anything and attempting to pull it together and then hiding / disabling the upload area when there's no ability to do so.

**Comment by mgifford** [comment]
Yup..  Having that URL works fine there.

**Comment by btopro** [comment]
upload button only shows up now if there's detected a backend which supports uploading
