### ISSUE TITLE
website game Make Paragraph = Too Hard

### ISSUE THREAD

**Issue by ElijahLynn** [LRNWebComponents/hax-body#147]
In the challenge one of the tasks is to make a paragraph, which is hard UX wise. I first went to "Find" which is logical, searched for paragraph and then text and no go. Then I saw "text" on the top bar, but that didn't check the box either. 

How do I create a paragraph?

**Comment by btopro** [comment]
Yeah I dono why that's so hard to trigger as an event. I had "delete p" and it wasn't noticing it in my mutation observer for whatever reason. I might just remove that from the game cause the point is to entice ppl to play w/ the UI not get hung up on simple things that they can do but I can't monitor 100% of the time. (if you type in a paragraph then hit enter to make a new one I think it triggers but not always; it's sily)

**Comment by ElijahLynn** [comment]
Yeah, I would remove it until it works, it definitely causes frustration e.g. Am I doing it wrong, what did I miss, is text not a paragraph?.

**Comment by btopro** [comment]
ha fair enough i'll do that now

**Comment by btopro** [comment]
rebuilding demo now
