### ISSUE TITLE
suggestion for hero images

### ISSUE THREAD

**Issue by kat-wehr** [LRNWebComponents/hax-body#149]
The placeholder texts for the hero image display should have the actual field titles in them in case the user doesn’t know what to put where right away. 

Like, the title field should display "Title" in the preview so people know what they are editing.

**Comment by btopro** [comment]
this might be a good one for you to jump in and issue pull requests on as they are stand alone elements which would supply that info

**Comment by kat-wehr** [comment]
i think i fixed it?

**Comment by btopro** [comment]
cool; now you need to issue the PR against the originating repo. You updated it in your repo via PR.

https://github.com/LRNWebComponents/hero-banner/compare

**Comment by kat-wehr** [comment]
lol alriiiiight I think I did that now. #babysfirstissue

**Comment by btopro** [comment]
nailed it!

**Comment by btopro** [comment]
@kat-wehr this is in master which means whenever we cut a new release (days maybe) then it'll find it's way up into elmsln. There's a build routine / timing involved but this at least ensures it'll be in there when the time comes :) woot
