### ISSUE TITLE
All code sections are labelled 'multi line' 

### ISSUE THREAD

**Issue by ellvix** [LRNWebComponents/hax-body#152]
Screen readers announce the label of the textarea thing that is the <juicy-ace-editor> as "multi line". 

Fix would be to add a label to the main textarea (connected label, aria-label, etc) at juicy-ace-editor > div#juicy-ace-editor-container > textarea.

**Comment by nikkimk** [comment]
The text editor itself is inaccessible to begin with. Researching a replacement...
