### ISSUE TITLE
Video title order

### ISSUE THREAD

**Issue by ellvix** [LRNWebComponents/hax-body#153]
The label / title thing on <video-player> elements comes after the video (DOM order). Technically this is still accessible, and is more of an annoyance or usability issue. The experience is that as a screen reader user moves through the page, they'll hit the video and have to decide what to do before they see the actual video title that comes below.

**Comment by btopro** [comment]
@nikkimk this would be a good one to resolve (if there's an easy way to accomplish this in its current form) in the video-player and or a11y-media-video tags. Thoughts on where that should go?
