### ISSUE TITLE
Hide tooltips for screen readers

### ISSUE THREAD

**Issue by ellvix** [LRNWebComponents/hax-body#154]
Tooltips (<paper-tooltip>) objects that appear in the main list of objects in the Make list do not have any text equivelent that screen readers can percieve, but they can be focused by the screen reader if the virtual cursor is being used (a common method). Result is that 'blank' is read in between each Make object. Bit of a confusing statement, easier to understand by describing the experience: 

A screen reader user arrows down through the page content like they always do. In the Make area, they hear "To Do List, blank, Basic iFrame, blank, Basic Image, blank, ..." 

This is not a bug or issue, but it would be a better experience to not have to hear those blanks (they appear all over the system). Fix would be to add an aria-hidden="true" to the <paper-tooltip> objects.

**Comment by btopro** [comment]
thanks for describing this so accurately. It was an oversight on my part, we didn't support tool tips on that element but it snuck into the design asset. Removed it.
