### ISSUE TITLE
Bullet Lists won't go past halfway

### ISSUE THREAD

**Issue by rickhumphries** [LRNWebComponents/hax-body#164]
As demonstrated here:

http://recordit.co/IB4IxyDWMR/

**Comment by btopro** [comment]
have you tried this in elmsln or https://github.com/elmsln/haxcms ? that's probably less a HAX issue and more a the silly minor css handling of that site

**Comment by rickhumphries** [comment]
That was on the demo site:
https://haxtheweb.org/components/hax-body/demo/

**Comment by rickhumphries** [comment]
Issue seems to be coming from `max-width` CSS on the haxtheweb.org site:
```
ul li {
    padding-bottom: 1.5em;
    line-height: 1.5;
    color: #424242;
    max-width: 28em;
```

**Comment by btopro** [comment]
ha thx
