### ISSUE TITLE
Unable to create Nasa meme to challenge's satisfaction

### ISSUE THREAD

**Issue by deppeler** [LRNWebComponents/hax-body#172]
I was able to find "create meme" and add "NASA" photo.  But, it did not detect "meme".  I tried to find way to add text to the photo, but did not figure this out before having to go back to my real job.

Thanks for a great time trying this and succeeding at several steps.  You are definitely on to something here.

**Comment by btopro** [comment]
ha, when you selected a nasa photo from the search did you pick Meme as the method of display? It's possible to complete this challenge though as we're currently in a refactor I don't have the bandwidth to fix this specific silly thing in the game :)

**Comment by deppeler** [comment]
great. When I get the chance, I'll return and try that order.


Thanks for a cool tool,

-Deb


________________________________
