### ISSUE TITLE
Top menu on haxtheweb 

### ISSUE THREAD

**Issue by jgonyea** [LRNWebComponents/hax-body#173]
The main menu items that load on mobile Firefox appears to run into each other. Image to be attached shortly. 

I apologize in advance if this is the wrong repo, but the website links directly to this one initially.

**Comment by jgonyea** [comment]
![Broken menu](https://i.imgur.com/NBSQ7cv.jpg)

**Comment by btopro** [comment]
Moving to the mono-repo. This isn't an issue w/ HAX but the tab-list item itself as it has almost no responsive capabilities (other then to space evenly)
