### ISSUE TITLE
Selection un-selects

### ISSUE THREAD

**Issue by aitala** [LRNWebComponents/hax-body#7]
After changing the style of selected text, the text is unselected.  It would be nice if it remained selected so that other styles could be applied, links added, list creation, etc.

**Comment by btopro** [comment]
this is unfortunately a safari specific issue and I'm not sure there's a way around. Safari actually applies focus to buttons and things clicked on by selecting them w/ the cursor where as no one browser does :)

**Comment by btopro** [comment]
I had to make a specific button to allow it to work at all because of this :0
