### ISSUE TITLE
Feedback: Usability of the Video Gizmo

### ISSUE THREAD

**Issue by zanesensenig** [LRNWebComponents/hax-body#8]
The target click area of the YouTube gizmo, when in editing mode, should be increased to improve usability. Currently, the only way to edit the video is by clicking a small button to the left of the gizmo. 

```
.responsive-video-container.video-player {
    max-width: 500px;
}
```

<img width="1680" alt="video-width" src="https://user-images.githubusercontent.com/4776824/33908093-48e259c6-df55-11e7-8520-21e1628c5e5a.png">

**Comment by btopro** [comment]
slightly larger though the 100% to the other side is just this demo; not sure if we could make it flow the rest of the way w.o. influencing the element but once we get integrated into elmsln we'll see.
